/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author jacqueline
 */
public class VtnAuxiliar extends javax.swing.JFrame {
    int numeroBarberos;
    VtnPrincipal objVtnPrincipal = null;
    
    /**
     * Creates new form VtnAuxiliar
     */
    public VtnAuxiliar() {
        initComponents();
        numeroBarberos = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInicio = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        txtNumeroBarberos = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInicio.setText("BIENVENIDO");

        lblPregunta.setText("¿Cuántos barberos desea tener?");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIniciar)
                    .addComponent(lblInicio))
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblPregunta)
                .addGap(30, 30, 30)
                .addComponent(txtNumeroBarberos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroBarberos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPregunta))
                .addGap(50, 50, 50)
                .addComponent(btnIniciar)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        int auxiliar = 0;
        auxiliar = comprobarEntrada();
        if (auxiliar != 0){
            if (objVtnPrincipal == null)
                objVtnPrincipal = new VtnPrincipal (this, numeroBarberos);
        
            objVtnPrincipal.setVisible(true);
            this.setVisible(false);
        }else{
            System.out.println("Error en la entrada de número de barberos");
            txtNumeroBarberos.setText("");
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    public int comprobarEntrada (){
        String entrada =  txtNumeroBarberos.getText();
        if (entrada.equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar una cantidad.");
            return 0;
        }
        else{
            boolean isNumeric = (entrada.matches("[0-9]+"));
            if (isNumeric = true){
                if (Integer.parseInt(entrada) <= 5){
                    numeroBarberos = Integer.parseInt(entrada);
                    return 1;
                }
                else {
                    JOptionPane.showMessageDialog(this, "En esta barbería cabemos máximo 5 barberos, usted y yo:)");
                    return 0;
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Ingrese una entrada válida");
                return 0;
            }
        }
        
        //Funciona con numeros pero se muere si ingresan letras
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAuxiliar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JTextField txtNumeroBarberos;
    // End of variables declaration//GEN-END:variables
}
